name: Update M3U Playlist

on:
  schedule:
    - cron: "0 */3 * * *"  # Run every 3 hours
  push:
    branches: [main]

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver

    - name: Create symbolic link if it doesn't exist
      run: |
        if [ ! -e /usr/bin/chromedriver ]; then sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver; fi

    - name: Run script
      run: |
        python update_playlist.py

    - name: Commit updated playlist
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add playlist.m3u
        git commit -m 'Update playlist with latest m3u8 links'
        git push
