name: Update Playlist

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT }}
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
    
    - name: Setup Git
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    - name: Clean workspace
      run: |
        # Remove untracked files
        git clean -fd
        # Discard local changes
        git checkout -- .
        # Pull latest changes
        git pull origin main
    
    - name: Update playlist
      run: python update_playlist.py
    
    - name: Commit and Push
      run: |
        # Add all files
        git add -A
        
        # Commit if there are changes
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          timestamp=$(date -u)
          git commit -m "Auto update playlist: ${timestamp}"
          git push origin main
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
